#include "adv_globals.h"

char *adventureMapLocations[] = {
  " ",
  "Alchemist Lab",
  "Sign",
  "Buoy",
  "Skeleton",
  "Daemon Cave",
  "Treasure Chest",
  "Faerie Ring",
  "Campfire",
  "Fountain",
  "Gazebo",
  "Ancient Lamp",
  "Graveyard",
  "Archer's House",
  "Goblin Hut",
  "Dwarf Cottage",
  "Peasant Hut",
  "Log Cabin",
  "Road",
  "Event",
  "Dragon City",
  "Lighthouse",
  "Water Wheel",
  "Mine",
  "Army Camp",
  "Obelisk",
  "Oasis",
  "Resource",
  " ",
  "Sawmill",
  "Oracle",
  "Shrine of the First Circle",
  "Shipwreck",
  "Sea Chest",
  "Desert Tent",
  "Town",
  "Stone Liths",
  "Wagon Camp",
  "Well",
  "Whirlpool",
  "Windmill",
  "Artifact",
  "Hero",
  "Boat",
  " ",
  "Random Artifact",
  "Random Resource",
  "Random Monster",
  "Random Town",
  "Random Castle",
  " ",
  "Random Monster - weak",
  "Random Monster - medium",
  "Random Monster - strong",
  "Random Monster - very strong",
  "Random Hero",
  "Nothing Special",
  " ",
  "Watch Tower",
  "Tree House",
  "Tree City",
  "Ruins",
  "Fort",
  "Trading Post",
  "Abandoned Mine",
  "Dwarf Cabin",
  "Standing Stones",
  "Idol",
  "Tree of Knowledge",
  "Witch Doctor's Hut",
  "Temple",
  "Hill Fort",
  "Halfling Hole",
  "Mercenary Camp",
  "Shrine of the Second Circle",
  "Shrine of the Third Circle",
  "Pyramid",
  "City of the Dead",
  "Excavation",
  "Sphinx",
  "Wagon",
  "Tar Pit",
  "Artesian Spring",
  "Troll Bridge",
  "Watering Hole",
  "Witch's Hut",
  "Xanadu",
  "Cave",
  "Lean-To",
  "Magellan's Maps",
  "Flotsam",
  "Derelict Ship",
  "Shipwreck Survivor",
  "Bottle",
  "Magic Well",
  "Magic Garden",
  "Observation Tower",
  "Freeman's Foundry",
  "Stream",
  "Trees",
  "Mountains",
  "Volcano",
  "Flowers",
  "Rock",
  "Lake",
  "Mandrake",
  "Dead Tree",
  "Stump",
  "Crater",
  "Cactus",
  "Mound",
  "Dune",
  "Lava Pool",
  "Shrub",
  "Hole",
  "Outcropping",
  "Random Artifact - Treasure",
  "Random Artifact - Minor",
  "Random Artifact - Major",
  "%s Barrier",
  "%s Traveller's Tent",
  "%s",
  "%s",
  "Jail",
  "Shipyard"
};

char *barrierColors[] = {
  "Aqua",
  "Blue",
  "Brown",
  "Gold",
  "Green",
  "Orange",
  "Purple",
  "Red"
};

char *expDwellingNames[] = {
  "Barrow Mounds",
  "Earth Summoning Altar",
  "Air Summoning Altar",
  "Fire Summoning Altar",
  "Water Summoning Altar"
};