#!/usr/local/bin/ruby

$LOAD_PATH.unshift(File.dirname(__FILE__))

require 'dir/structure.rb'
require 'import/types.rb'
require 'import/funcs.rb'
require 'expose/expose.rb'
require 'expand/template.rb'

case ARGV[0]
when "init"
  dir = Seance::Directory.new(ARGV[1])
  dir.init_seance

when "add-header"
  Seance::Import.import_header(ARGV[1], ".")

when "expose-type"
  ARGV[1..-1].each do |w|
    Seance::Expose.expose_type(w, ".")
  end

when "expose-func"
  ARGV[1..-1].each do |w|
    Seance::Expose.expose_func(w, ".")
  end
 
when "add-func"
  ARGV[1..-1].each do |w|
    begin
      puts "Processing #{w}"
      Seance::Import.import_func(w, ".")
    rescue Seance::Import::ImportException => e
      puts e.message
    end
  end

when "create-subproject"
  Seance::Directory::make_subproject(".", ARGV[1])

when "create-source"
  Seance::Expand.reify_templates(".", ARGV[1])

else
  puts "Invalid command"
  
end
