#include "spell/spell_constants.h"

char *gSpellNames[] = {
  "Fireball",
  "Fireblast",
  "Lightning Bolt",
  "Chain Lightning",
  "Teleport",
  "Cure",
  "Mass Cure",
  "Resurrect",
  "Resurrect True",
  "Haste",
  "Mass Haste",
  "Slow",
  "Mass Slow",
  "Blind ",
  "Bless",
  "Mass Bless",
  "Stoneskin",
  "Steelskin",
  "Curse",
  "Mass Curse",
  "Holy Word",
  "Holy Shout",
  "Anti-Magic",
  "Dispel Magic",
  "Mass Dispel",
  "Magic Arrow",
  "Berzerker",
  "Armageddon",
  "Elemental Storm",
  "Meteor Shower",
  "Paralyze",
  "Hypnotize",
  "Cold Ray",
  "Cold Ring",
  "Disrupting Ray",
  "Death Ripple",
  "Death Wave",
  "Dragon Slayer",
  "Blood Lust",
  "Animate Dead",
  "Mirror Image",
  "Shield",
  "Mass Shield",
  "Summon Earth Elemental",
  "Summon Air Elemental",
  "Summon Fire Elemental",
  "Summon Water Elemental",
  "Earthquake",
  "View Mines",
  "View Resources",
  "View Artifacts",
  "View Towns",
  "View Heroes",
  "View All",
  "Identify Hero",
  "Summon Boat",
  "Dimension Door",
  "Town Gate",
  "Town Portal",
  "Visions",
  "Haunt",
  "Set Earth Guardian",
  "Set Air Guardian",
  "Set Fire Guardian",
  "Set Water Guardian",
  "Awareness",
  "Shadow Mark",
  "Marksman Pierce",
  "Plasma Cone",
  "Force Shield",
  "Mass Force Shield",
  "Fire Bomb",
  "Implosion Grenade"
};