 IMPORT__EXIT = 1
 _WinMainCRTStartup EQU _start_asm
 IMPORT_?OLDMAIN@@YIHXZ = 1
??2@YAPAXI@Z EQU _op_new
IMPORT_??2@YAPAXI@Z = 1
??3@YAXPAX@Z EQU _op_del
IMPORT_??3@YAXPAX@Z = 1

bMenu EQU ?bMenu@@3PAUMainWindow@@A

??_7textEntryWidget@@6B@ EQU ?textEntryWidget_vftable@@3UwidgetVtable@@A
??_7border@@6B@ EQU ?border_vftable@@3UwidgetVtable@@A
??_7textWidget@@6B@ EQU ?textWidget_vftable@@3UwidgetVtable@@A
??_7button@@6B@ EQU ?button_vftable@@3UwidgetVtable@@A
??_7dimmerWidget@@6B@ EQU ?dimmerWidget_vftable@@3UwidgetVtable@@A
??_7listBoxWidget@@6B@ EQU ?listBoxWidget_vftable@@3UwidgetVtable@@A
??_7dropListWidget@@6B@ EQU ?dropListWidget_vftable@@3UwidgetVtable@@A
??_7iconWidget@@6B@ EQU ?iconWidget_vftable@@3UwidgetVtable@@A
