#ifndef TIED_SKILLS_H
#define TIED_SKILLS_H


enum PRIMARY_SKILL {
  PRIMARY_SKILL_ATTACK = 0,
  PRIMARY_SKILL_DEFENSE = 1,
  PRIMARY_SKILL_SPELLPOWER = 2,
  PRIMARY_SKILL_KNOWLEDGE = 3,
  NUM_PRIMARY_SKILLS = 4
};

enum SECONDARY_SKILL {
  SECONDARY_SKILL_PATHFINDING = 0,
  SECONDARY_SKILL_ARCHERY = 1,
  SECONDARY_SKILL_LOGISTICS = 2,
  SECONDARY_SKILL_SCOUTING = 3,
  SECONDARY_SKILL_DIPLOMACY = 4,
  SECONDARY_SKILL_NAVIGATION = 5,
  SECONDARY_SKILL_LEADERSHIP = 6,
  SECONDARY_SKILL_WISDOM = 7,
  SECONDARY_SKILL_MYSTICISM = 8,
  SECONDARY_SKILL_LUCK = 9,
  SECONDARY_SKILL_BALLISTICS = 10,
  SECONDARY_SKILL_EAGLE_EYE = 11,
  SECONDARY_SKILL_NECROMANCY = 12,
  SECONDARY_SKILL_ESTATES = 13,
  NUM_SECONDARY_SKILLS = 14
};

struct startingPrimarySkills {
  __int8 attack;
  __int8 defense;
  __int8 spellPower;
  __int8 knowledge;
  __int8 unused;
};

extern char *gSecondarySkills[];
extern char *secondarySkillLevels[];

#endif