
  char color;
  char numHeroes;
  char curHeroIdx;
  char field_3;
  char heroesOwned[8];
  char heroesForPurchase[2];
  char _2;
  int personality;
  char _3[45];
  char field_40;
  __int16 field_41;
  char field_43;
  char numCastles;
  __int16 field_45;
  char castlesOwned[72];
  int resources[7];
  char _4[111];
  char field_11A;
