{
  icon::CombatClipDrawToBuffer(
    gpCombatManager->combatObjIcons[this->combatObjIdx],
    this->centerX,
    this->occupyingCreatureBottomY,
    0,
    &this->drawingBounds,
    0,
    0,
    0,
    0);
}