#ifndef TIED_SKILLS_H
#define TIED_SKILLS_H


#define PRIMARY_SKILL_ATTACK       0
#define PRIMARY_SKILL_DEFENSE      1
#define PRIMARY_SKILL_SPELLPOWER   2
#define PRIMARY_SKILL_KNOWLEDGE    3

#endif