
  AI_BATTLEFIELD_AFFECTING_SPELL = 0x0,
  AI_MASS_BUFF_SPELL = 0x1,
  AI_MASS_DEBUFF_SPELL = 0x2,
  AI_BALL_SPALL = 0x3,
  AI_TARGET_BUFF_SPELL = 0x4,
  AI_TARGET_DAMAGE_OR_DEBUFF_SPELL = 0x5,
  AI_RESURRECT_SPELL = 0x6,
  AI_DISPEL_SPELL = 0x7,
