
  CREATURE_COMBAT_MOVE_SOUND = 0x0,
  CREATURE_COMBAT_ATTACK_SOUND = 0x1,
  CREATURE_COMBAT_WINCE_SOUND = 0x2,
  CREATURE_COMBAT_SHOT_SOUND = 0x3,
  CREATURE_COMBAT_KILL_SOUND = 0x4,
  CREATURE_COMBAT_EXTRA_SOUND_1 = 0x5,
  CREATURE_COMBAT_EXTRA_SOUND_2 = 0x6,
