#ifndef TOWN_GLOBALS_H
#define TOWN_GLOBALS_H

#include <vector>
#include "adventure/adv.h"

#pragma pack(push,1)

unsigned long gTownEligibleBuildMask[];

#define MAX_CASTLES 72
#define NUM_ORIG_FACTIONS 6

enum HERO_TYPE
{
	HERO_TYPE_KNIGHT = 0,
	HERO_TYPE_BARBARIAN = 1,
	HERO_TYPE_SORCERESS = 2,
	HERO_TYPE_WARLOCK = 3,
	HERO_TYPE_WIZARD = 4,
	HERO_TYPE_NECROMANCER = 5,
	HERO_TYPE_KNIGHT_CAPTAIN = 6,
	HERO_TYPE_BARBARIAN_CAPTAIN = 7,
	HERO_TYPE_SORCERESS_CAPTAIN = 8,
	HERO_TYPE_WARLOCK_CAPTAIN = 9,
	HERO_TYPE_WIZARD_CAPTAIN = 10,
	HERO_TYPE_NECROMANCER_CAPTAIN = 11,
	HERO_TYPE_CYBORG = 12,
	HERO_TYPE_CYBORG_CAPTAIN = 18
};

enum FACTION
{
	FACTION_KNIGHT = 0,
	FACTION_BARBARIAN = 1,
	FACTION_SORCERESS = 2,
	FACTION_WARLOCK = 3,
	FACTION_WIZARD = 4,
	FACTION_NECROMANCER = 5,
	FACTION_MULTIPLE = 6,
	FACTION_RANDOM = 7,

	FACTION_CYBORG = 12,
	MAX_FACTIONS
};

enum BUILDING_CODE : __int8
{
  BUILDING_INVALID = -1,
  BUILDING_MAGE_GUILD = 0x0,
  BUILDING_THIEVES_GUILD = 0x1,
  BUILDING_TAVERN = 0x2,
  BUILDING_DOCK = 0x3,
  BUILDING_WELL = 0x4,
  BUILDING_TENT = 0x5,
  BUILDING_CASTLE = 0x6,
  BUILDING_STATUE = 0x7,
  BUILDING_LEFT_TURRET = 0x8,
  BUILDING_RIGHT_TURRET = 0x9,
  BUILDING_MARKET = 0xA,
  BUILDING_SPECIAL_GROWTH = 0xB,
  BUILDING_MOAT = 0xC,
  BUILDING_SPECIAL = 0xD,
  BUILDING_BOAT = 0xE,
  BUILDING_CAPTAIN = 0xF,
  BUILDING_EXT_0 = 0x10,
  BUILDING_EXT_1 = 0x11,
  BUILDING_EXT_2 = 0x12,
  BUILDING_DWELLING_1 = 0x13,
  BUILDING_DWELLING_2 = 0x14,
  BUILDING_DWELLING_3 = 0x15,
  BUILDING_DWELLING_4 = 0x16,
  BUILDING_DWELLING_5 = 0x17,
  BUILDING_DWELLING_6 = 0x18,
  //Why is "upgrade 1" an upgrade to dwelling 2?
  //Don't know; these names were found in the executable
  BUILDING_UPGRADE_1 = 0x19,
  BUILDING_UPGRADE_2 = 0x1A,
  BUILDING_UPGRADE_3 = 0x1B,
  BUILDING_UPGRADE_4 = 0x1C,
  BUILDING_UPGRADE_5 = 0x1D,
  BUILDING_UPGRADE_5B = 0x1E,
  BUILDING_EXT_3 = 0x1F,
  BUILDING_MAX
};

enum DWELLING_TYPE
{
  DWELLING_1,
  DWELLING_2,
  DWELLING_3,
  DWELLING_4,
  DWELLING_5,
  DWELLING_6,
  DWELLING_2_UPGRADE,
  DWELLING_3_UPGRADE,
  DWELLING_4_UPGRADE,
  DWELLING_5_UPGRADE,
  DWELLING_6_UPGRADE,
  DWELLING_6_UPGRADE2,
  NUM_DWELLINGS
};

extern std::vector<FACTION> FACTIONS_ACTUAL;
extern std::vector<std::string> FACTIONS_ACTUAL_NAMES;

// Order matters here. The original game indexes into gTownObjNames to
// access elements of gDwellingType.
extern char *gTownObjNames[];
extern unsigned char gDwellingType[][NUM_DWELLINGS];
extern char *gTownPrefixNames[MAX_FACTIONS];

void InitTownObjNames();
void InitDwellingTypes();
void InitBuildingNames();

#pragma pack(pop)

#endif
